#!/bin/bash

set -e

clang++-7 -o bin/assignment2 source/assignment2.cpp `llvm-config-7 --cxxflags` `llvm-config-7 --ldflags` `llvm-config-7 --libs` -lpthread -lncurses -ldl -Wno-unknown-warning-option

./bin/assignment2 llvms/assignment2-example4.ll