#!/bin/bash

set -e

clang++-7 -o bin/assignment2 source/assignment2.cpp `llvm-config-7 --cxxflags` `llvm-config-7 --ldflags` `llvm-config-7 --libs` -lpthread -lncurses -ldl -Wno-unknown-warning-option
clang-7 -emit-llvm -fno-discard-value-names -S -o llvms/assignment2-example4.ll target/assignment2-example4.c
./bin/assignment2 llvms/assignment2-example4.ll