#!/bin/sh

#example: sh setup-git.sh "name" "test@test.com"

name="$1"
email="$2"

ssh-keygen -t rsa -b 4096 -C $email
ssh-add ~/.ssh/id_rsa
code ~/.ssh/id_rsa.pub

git config --global user.name $name
git config --global user.email $email

git config --global merge.tool vscode
git config --global mergetool.vscode.cmd "code --wait $MERGED"
git config --global diff.tool vscode
git config --global difftool.vscode.cmd "code --wait --diff $LOCAL $REMOTE"