#!/bin/bash

opt-7 -dot-cfg llvms/test1.ll
mv cfg.main.dot graphs/test1.dot

opt-7 -dot-cfg llvms/test2.ll
mv cfg.main.dot graphs/test2.dot

opt-7 -dot-cfg llvms/test3.ll
mv cfg.main.dot graphs/test3.dot

opt-7 -dot-cfg llvms/test4.ll
mv cfg.main.dot graphs/test4.dot

opt-7 -dot-cfg llvms/assignment1-task2.ll
mv cfg.main.dot graphs/assignment1-task2.dot

opt-7 -dot-cfg llvms/assignment1-task3.ll
mv cfg.main.dot graphs/assignment1-task3.dot

opt-7 -dot-cfg llvms/assignment2-example1.ll
mv cfg.main.dot graphs/assignment2-example1.dot

opt-7 -dot-cfg llvms/assignment2-example2.ll
mv cfg.main.dot graphs/assignment2-example2.dot

opt-7 -dot-cfg llvms/assignment2-example3.ll
mv cfg.main.dot graphs/assignment2-example3.dot

opt-7 -dot-cfg llvms/assignment2-example4.ll
mv cfg.main.dot graphs/assignment2-example4.dot

opt-7 -dot-cfg llvms/assignment3-example1.ll
mv cfg.main.dot graphs/assignment3-example1.dot

opt-7 -dot-cfg llvms/assignment3-example2.ll
mv cfg.main.dot graphs/assignment3-example2.dot

opt-7 -dot-cfg llvms/assignment3-example3.ll
mv cfg.main.dot graphs/assignment3-example3.dot

cd graphs
./allfigs2pdf