#!/bin/bash

clang-7 -emit-llvm -fno-discard-value-names -S -o llvms/test1.ll target/test1.c
clang-7 -emit-llvm -fno-discard-value-names -S -o llvms/test2.ll target/test2.c
clang-7 -emit-llvm -fno-discard-value-names -S -o llvms/test3.ll target/test3.c
clang-7 -emit-llvm -fno-discard-value-names -S -o llvms/test4.ll target/test4.c

clang-7 -emit-llvm -fno-discard-value-names -S -o llvms/assignment1-task2.ll target/assignment1-task2.c
clang-7 -emit-llvm -fno-discard-value-names -S -o llvms/assignment1-task3.ll target/assignment1-task3.c

clang-7 -emit-llvm -fno-discard-value-names -S -o llvms/assignment2-example1.ll target/assignment2-example1.c
clang-7 -emit-llvm -fno-discard-value-names -S -o llvms/assignment2-example2.ll target/assignment2-example2.c
clang-7 -emit-llvm -fno-discard-value-names -S -o llvms/assignment2-example3.ll target/assignment2-example3.c
clang-7 -emit-llvm -fno-discard-value-names -S -o llvms/assignment2-example4.ll target/assignment2-example4.c