#!/bin/bash

echo "Compile Assignment 1 Task 2"
clang++-7 -o binary/assignment1-task2 assignment1/task2.cpp `llvm-config-7 --cxxflags` `llvm-config-7 --ldflags` `llvm-config-7 --libs` -lpthread -lncurses -ldl -Wno-unknown-warning-option

echo "Run Assignment 1 Task 2 against test1"
./binary/assignment1-task2 llvms/assignment1-test.ll